#!/usr/bin/env node
// Generates `src/version.ts` from `package.json`'s `version` field, so
// bumping a release means editing `package.json` and nothing else.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const pkg = JSON.parse(readFileSync(`${root}package.json`, "utf8"));

const output = `/**
 * Generated by \`npm run generate:version\` from \`package.json\`'s \`version\`
 * field. Do not edit by hand: bumping a release means editing
 * \`package.json\` and nothing else.
 */

/**
 * The published version of this package, for tagging telemetry so a newly
 * released rule set can be measured on its own.
 */
export const version = "${pkg.version}";
`;

writeFileSync(`${root}src/version.ts`, output);
